import React from 'react';
import { FileText, AlertCircle } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/**
 * ExportTimetable Utility
 * Handles exporting timetables to PDF
 */
export async function exportTimetableAsPDF(timetable, filename = 'timetable.pdf') {
  try {
    // Create a temporary container
    const container = document.createElement('div');
    container.style.padding = '20px';
    container.style.backgroundColor = 'white';
    container.style.width = '1200px';
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    
    // Build HTML for export
    container.innerHTML = `
      <h1 style="text-align: center; font-size: 24px; margin-bottom: 20px;">
        Course Timetable
      </h1>
      
      <div style="margin-bottom: 20px; text-align: center;">
        <p><strong>Total Credits:</strong> ${timetable.total_credits}</p>
        <p><strong>Courses:</strong> ${timetable.course_codes.join(', ')}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead>
          <tr style="background-color: #f0f0f0;">
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Course Code</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Course Name</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Slot</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Faculty</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Timings</th>
            <th style="border: 1px solid #ddd; padding: 10px; text-align: center;">Credits</th>
          </tr>
        </thead>
        <tbody>
          ${timetable.slots.map(slot => `
            <tr>
              <td style="border: 1px solid #ddd; padding: 10px;"><strong>${slot.course_code}</strong></td>
              <td style="border: 1px solid #ddd; padding: 10px;">${slot.course_name}</td>
              <td style="border: 1px solid #ddd; padding: 10px;">${slot.slot_number}</td>
              <td style="border: 1px solid #ddd; padding: 10px;">${slot.faculty_name}</td>
              <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px;">
                ${slot.time_blocks.map(tb => `${tb.day} ${tb.start_time}-${tb.end_time}`).join('<br/>')}
              </td>
              <td style="border: 1px solid #ddd; padding: 10px; text-align: center;">${slot.credits}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div style="margin-top: 30px; font-size: 12px; color: #666;">
        <p>Generated by IntelliPlan - AI-Powered Course Scheduler</p>
        <p>Generated on: ${new Date().toLocaleString()}</p>
      </div>
    `;

    document.body.appendChild(container);

    // Convert HTML to canvas
    const canvas = await html2canvas(container, {
      backgroundColor: '#ffffff',
      scale: 2,
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = pdf.internal.pageSize.getWidth();
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
    pdf.save(filename);

    // Cleanup
    document.body.removeChild(container);

    return { success: true, message: 'Timetable exported successfully' };
  } catch (error) {
    console.error('PDF Export Error:', error);
    return { success: false, error: error.message };
  }
}

/**
 * ExportModal Component
 */
export default function ExportModal({ timetable, onClose, onConfirm }) {
  const handleExport = async () => {
    const result = await exportTimetableAsPDF(
      timetable,
      `timetable_${new Date().getTime()}.pdf`
    );
    
    if (result.success) {
      onConfirm?.();
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-lg max-w-md w-full p-6">
        <div className="flex items-center gap-3 mb-4">
          <FileText className="text-blue-600" size={24} />
          <h2 className="text-xl font-bold text-gray-900">Export Timetable</h2>
        </div>

        <p className="text-gray-600 mb-6">
          Download your timetable as a PDF file. You can save it locally or print it.
        </p>

        <div className="bg-blue-50 border border-blue-200 rounded p-4 mb-6">
          <div className="flex gap-2 text-sm">
            <AlertCircle className="text-blue-600 flex-shrink-0" size={18} />
            <p className="text-gray-700">
              Make sure you're satisfied with this timetable before exporting.
            </p>
          </div>
        </div>

        <div className="flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-2 border border-gray-300 text-gray-900 rounded-lg hover:bg-gray-50 transition font-semibold"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition font-semibold flex items-center justify-center gap-2"
          >
            <FileText size={18} />
            Export as PDF
          </button>
        </div>
      </div>
    </div>
  );
}
